//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ElectronicBooks = new HashSet<ElectronicBook>();
            this.Phones = new HashSet<Phone>();
            this.SmartWatches = new HashSet<SmartWatch>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ElectronicBook> ElectronicBooks { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<SmartWatch> SmartWatches { get; set; }
    }
}
