//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartWatch
    {
        public int Id { get; set; }
        public Nullable<int> InterfaceForConnectingId { get; set; }
        public Nullable<double> ScreenDiagonal { get; set; }
        public Nullable<bool> Pulsometer { get; set; }
        public Nullable<bool> SimCard { get; set; }
        public int ProductId { get; set; }
    
        public virtual InterfaceForConnecting InterfaceForConnecting { get; set; }
        public virtual Product Product { get; set; }
    }
}
